spring:
  profiles:
    active: local
    group:
      local: [local, common, secret]
      blue:  [blue,  common, secret]
      green: [green, common, secret]

# ---- local ----------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: local

server:
  env: local
  port: 8080
  address: 0.0.0.0
serverName: local_server

# ---- blue (EC2) ----------------------------------------------
---
spring:
  config:
    activate:
      on-profile: blue

server:
  env: blue
  port: 8080
  address: 0.0.0.0
serverName: blue_server

# ---- green (EC2) ---------------------------------------------
---
spring:
  config:
    activate:
      on-profile: green

server:
  env: green
  port: 8080
  address: 0.0.0.0
serverName: green_server

# ---- common ---------------------------------------------------
---
spring:
  config:
    activate:
      on-profile: common

  springdoc:
    swagger-ui:
      enable: true
      enabled: true
    api-docs:
      enabled: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql: true
        
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.DefaultRestClient: OFF
